import { Typography } from "@mui/material";
import { ReactNode } from "react";

export const SummarAIsePreview = ({ summary }: { summary: ReactNode }) => {
  const facilityName = "ABC Hospital";
  const doctorName = "Dr. Paul";
  const patientName = "John Doe";
  return (
    <div className="relative p-2 rounded-md border-1 border-gray-300 shadow-md">
      <Typography variant="body1">Dear Sir/Madam,</Typography>
      <br />
      <Typography variant="body1">
        You are receiving this report as the registered caregiver of{" "}
        {patientName}.
      </Typography>
      <br />
      <Typography variant="body1">
        On{" "}
        {new Date().toLocaleDateString("en-SG", {
          weekday: "long",
          day: "numeric",
          month: "long",
          year: "numeric",
        })}{" "}
        at {facilityName}, {patientName} attended a consulation with{" "}
        {doctorName}. Below is a summary of the session:
      </Typography>
      <br />
      {summary}
      <br />
      <Typography variant="body1">
        Please contact {facilityName} (+65 9876 5432 | abchospital@abc.org)
        should you require more information.
      </Typography>
      <Typography variant="caption">
        This report was generated by SummarAIser.
      </Typography>
    </div>
  );
};
